# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

warnings_are_errors: true

sudo: required

r_binary_packages:
  - XML
  - Rcpp
  - knitr

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
